import koneksi.koneksi2;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class fromsiswa extends javax.swing.JFrame {

    public fromsiswa() {
        initComponents();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nn1 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        nn = new javax.swing.JLabel();
        jenis = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jurusan = new javax.swing.JComboBox<>();
        jenis1 = new javax.swing.JLabel();
        jenis2 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        semester = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        nn1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        nn1.setForeground(new java.awt.Color(255, 255, 255));
        nn1.setText("JENIS KELAMIN");

        nim.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N

        nama.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N

        nn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        nn.setForeground(new java.awt.Color(255, 255, 255));
        nn.setText("Jurusan");

        jenis.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jenis.setForeground(new java.awt.Color(255, 255, 255));
        jenis.setText("Nim");

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FROM SISWA");

        laki.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        laki.setText("Laki-Laki");

        perempuan.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        perempuan.setText("Perempuan");

        jurusan.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***Silankan Pilih***", "RPL", "TSM", "TKR" }));

        jenis1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jenis1.setForeground(new java.awt.Color(255, 255, 255));
        jenis1.setText("Nama Siswa");

        jenis2.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jenis2.setForeground(new java.awt.Color(255, 255, 255));
        jenis2.setText("Semester");

        keluar.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        batal.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        simpan.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        cari.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        ubah.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nim", "Nama siswa", "Jenis kelamin", "Jurusan", "Semester"
            }
        ));
        tabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(simpan)
                                .addGap(49, 49, 49)
                                .addComponent(batal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ubah)))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keluar)
                            .addComponent(hapus)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nn1)
                            .addComponent(nn)
                            .addComponent(jenis2)
                            .addComponent(jenis)
                            .addComponent(jenis1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(laki)
                                .addGap(18, 18, 18)
                                .addComponent(perempuan))
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenis)
                            .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenis1)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(nn))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(nn1)))
                                .addGap(18, 18, 18)
                                .addComponent(jenis2)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(laki)
                                    .addComponent(perempuan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(simpan)
                            .addComponent(hapus)
                            .addComponent(batal))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ubah)
                            .addComponent(cari)
                            .addComponent(keluar)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
        if (baris != -1) {
            nim.setText(tabel.getValueAt(baris, 0).toString());
            nama.setText(tabel.getValueAt(baris, 1).toString());
            if ("Laki-Laki".equals (tabel.getValueAt(baris, 1).toString())){
                laki.setSelected(true);
            }
            else {
                perempuan.setSelected(true);
            }
            jurusan.setSelectedItem(tabel.getValueAt(baris, 3).toString());
            semester.setText(tabel.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void tabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelAncestorAdded

    private void semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini?",
            "Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
        if(ok == 0) {
            String sql="DELETE FROM mahasiswa WHERE Nim='"+ nim.getText().trim()+"'";
            try{
                java.sql.Statement stat = koneksi2.GetConnection().createStatement();
                stat.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Berhasil di Hapus", "Hapus Data"
                    ,JOptionPane.INFORMATION_MESSAGE);
                stat.close();
                nim.setText("");
                nama.setText("");
                jurusan.setSelectedIndex(-0);
                semester.setText("");
                nim.requestFocus();
                TampilData();
            }
            catch (SQLException exc) {
                System.err.println(sql);
                System.err.println("Error : "+exc);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String Nim = nim.getText();
        String Nama = nama.getText();
        String jeniskelamin = null;
        if(laki.isSelected()){
            jeniskelamin="laki-laki";
        }
        else if(perempuan.isSelected()){
            jeniskelamin="perempuan";
        }
        String jurus=jurusan.getSelectedItem().toString();
        String nama1=nama.getText();
        String nim1=nim.getText();
        String semester1=semester.getText();
        if(nim.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"mohon masukan data untuk di input",
                "PERHATIAN",JOptionPane.WARNING_MESSAGE);
        }

        else{
            try{
                java.sql.Statement stat =koneksi2.GetConnection().createStatement();
                ResultSet data= stat.executeQuery("SELECT*FROM mahasiswa "
                    + "WHERE nim ='"+nim.getText()+"'");
                if(data.next()){
                    JOptionPane.showMessageDialog(null, "nim sudah ada","PERHATIAN",
                        JOptionPane.WARNING_MESSAGE);
                    nim.requestFocus();
                }
                else{
                    String sql="INSERT INTO mahasiswa VALUES ('"+nim1+"'"
                    +",'"+nama1+"'"
                    +",'"+jeniskelamin+"'"
                    +",'"+jurus+"'"
                    +",'"+semester1+"')" ;
                    stat.executeUpdate(sql);
                    nim.setText("");
                    nama.setText("");
                    jurusan.setSelectedIndex(-0);
                    semester.setText("");
                    nim.requestFocus();
                    JOptionPane.showMessageDialog(null, "data berhasil disimpan","SUKSES",
                        JOptionPane.INFORMATION_MESSAGE);
                    TampilData();
                }
                stat.close();
            }catch (Exception exc){
                System.out.println("Terjadi Kesalahan :" + exc);
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        nim.setText("");
        nama.setText("");
        laki.setSelected(false);
        perempuan.setSelected(false);
        jurusan.setSelectedIndex(-0);
        semester.setText("");
    }//GEN-LAST:event_batalActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null,"yakin mau keluar ?",
            "konfirmasi",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromsiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromsiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromsiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromsiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromsiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jenis;
    private javax.swing.JLabel jenis1;
    private javax.swing.JLabel jenis2;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JButton keluar;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JLabel nn;
    private javax.swing.JLabel nn1;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JTextField semester;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

    private void TampilData() {
     DefaultTableModel model=new DefaultTableModel();
         model.addColumn("Nim");
         model.addColumn("Nama_Siswa");
         model.addColumn("Jenis_Kelamin");
         model.addColumn("Jurusan");
         model.addColumn("Semester");
         tabel.setModel(model);
         //menampilkan data database kedalam tabel
         try{
            java.sql.Statement stat=koneksi2.GetConnection().createStatement();
            ResultSet data= stat.executeQuery
            ("SELECT * FROM mahasiswa");
            while(data.next()){
               model.addRow(new Object[]{
               data.getString("NIM"),
               data.getString("Nama_Siswa"),
               data.getString("jenis_kelamin"),
               data.getString("Jurusan"),
               data.getString("Semester")             
               });
               tabel.setModel(model);
            }
         }
         catch(Exception e){
            System.err.println("terjadi kesalahan" +e );
        }
    }
}
